<?php
session_start();
require_once '../config/database.php';
require_once '../includes/functions.php';

// Admin or Secretary access
require_admin();

$page_title = "Reports - CHMSU BAO";
$base_url = "..";

// Get current date and time for report header
$current_date = date('F j, Y');
$current_time = date('g:i A');
?>

<?php include '../includes/header.php'; ?>

<style>
	.report-header {
		background: linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%);
		color: white;
		border-top: 4px solid #fbbf24;
	}
	.report-header-content {
		background: white;
		border-left: 4px solid #1e3a8a;
	}
	.report-card {
		transition: all 0.3s ease;
		border-left: 4px solid transparent;
	}
	.report-card:hover {
		transform: translateY(-2px);
		border-left-color: #1e3a8a;
		box-shadow: 0 10px 25px rgba(0,0,0,0.1);
	}
	.report-icon {
		width: 48px;
		height: 48px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 8px;
	}
</style>

<div class="flex h-screen bg-gray-100">
	<?php include '../includes/admin_sidebar.php'; ?>
	
	<div class="flex-1 flex flex-col overflow-hidden">
		<!-- Top header -->
		<header class="bg-white shadow-sm z-10">
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
				<h1 class="text-2xl font-semibold text-gray-900">Reports</h1>
				<div class="flex items-center">
					<span class="text-gray-700 mr-2"><?php echo $_SESSION['user_name']; ?></span>
					<button class="md:hidden rounded-md p-2 inline-flex items-center justify-center text-gray-500 hover:text-gray-600 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500" id="menu-button">
						<span class="sr-only">Open menu</span>
						<i class="fas fa-bars"></i>
					</button>
				</div>
			</div>
		</header>
		
		<!-- Main content -->
		<main class="flex-1 overflow-y-auto p-4 bg-gray-50">
			<div class="max-w-7xl mx-auto">
				<!-- Professional Report Header -->
				<div class="report-header rounded-t-lg mb-6">
					<div class="px-8 py-6">
						<div class="text-center">
							<h1 class="text-3xl font-bold mb-2">BUSINESS AFFAIRS OFFICE REPORTS</h1>
							<p class="text-lg font-medium mb-1">CITY OF TALISAY, Province of Negros Occidental</p>
							<p class="text-sm opacity-90">CHMSU - Carlos Hilado Memorial State University</p>
						</div>
					</div>
				</div>
				
				<!-- Report Information Section -->
				<div class="report-header-content rounded-b-lg shadow-lg mb-6 p-6">
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
						<div>
							<p class="text-gray-600 mb-1"><strong>Generated on:</strong> <?php echo $current_date; ?> at <?php echo $current_time; ?></p>
							<p class="text-gray-600"><strong>Generated by:</strong> <?php echo htmlspecialchars($_SESSION['user_name']); ?></p>
						</div>
						<div>
							<p class="text-gray-600 mb-1"><strong>Report Period:</strong> All Available Reports</p>
							<p class="text-gray-600"><strong>Office:</strong> Business Affairs Office</p>
						</div>
					</div>
				</div>
				
				<!-- Report tiles -->
				<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
					<a href="gym_reports.php?report_type=usage" class="report-card bg-white rounded-lg shadow-md p-6">
						<div class="flex items-start gap-4">
							<div class="report-icon bg-blue-100 text-blue-600 flex-shrink-0">
								<i class="fas fa-dumbbell text-xl"></i>
							</div>
							<div class="flex-1">
								<h2 class="text-lg font-bold text-gray-900 mb-2">Gym Reservation Report</h2>
								<p class="text-sm text-gray-600 leading-relaxed">View bookings by date, facility, and status. Track gymnasium utilization and booking trends.</p>
							</div>
						</div>
					</a>
					<a href="bus_reports.php" class="report-card bg-white rounded-lg shadow-md p-6">
						<div class="flex items-start gap-4">
							<div class="report-icon bg-emerald-100 text-emerald-600 flex-shrink-0">
								<i class="fas fa-bus text-xl"></i>
							</div>
							<div class="flex-1">
								<h2 class="text-lg font-bold text-gray-900 mb-2">Bus Reservation Report</h2>
								<p class="text-sm text-gray-600 leading-relaxed">Monitor bus requests, destinations, kilometers traveled, costs, and approval status.</p>
							</div>
						</div>
					</a>
					<a href="inventory_reports.php" class="report-card bg-white rounded-lg shadow-md p-6">
						<div class="flex items-start gap-4">
							<div class="report-icon bg-purple-100 text-purple-600 flex-shrink-0">
								<i class="fas fa-box text-xl"></i>
							</div>
							<div class="flex-1">
								<h2 class="text-lg font-bold text-gray-900 mb-2">Item Request / Inventory</h2>
								<p class="text-sm text-gray-600 leading-relaxed">Track issued items vs stock levels and inventory movement by category.</p>
							</div>
						</div>
					</a>
					<a href="billing_reports.php" class="report-card bg-white rounded-lg shadow-md p-6">
						<div class="flex items-start gap-4">
							<div class="report-icon bg-green-100 text-green-600 flex-shrink-0">
								<i class="fas fa-file-invoice-dollar text-xl"></i>
							</div>
							<div class="flex-1">
								<h2 class="text-lg font-bold text-gray-900 mb-2">Billing Summary</h2>
								<p class="text-sm text-gray-600 leading-relaxed">Analyze paid vs pending transactions by service type and payment status.</p>
							</div>
						</div>
					</a>
					<a href="summary_reports.php" class="report-card bg-white rounded-lg shadow-md p-6">
						<div class="flex items-start gap-4">
							<div class="report-icon bg-red-100 text-red-600 flex-shrink-0">
								<i class="fas fa-chart-line text-xl"></i>
							</div>
							<div class="flex-1">
								<h2 class="text-lg font-bold text-gray-900 mb-2">Daily / Monthly Summary</h2>
								<p class="text-sm text-gray-600 leading-relaxed">Comprehensive overview of requests, approvals, collections, and top services.</p>
							</div>
						</div>
					</a>
				</div>
				
				<!-- Report Footer -->
				<div class="mt-8 bg-white rounded-lg shadow-md p-6 border-t-2 border-gray-200">
					<div class="text-center">
						<p class="text-sm font-semibold text-gray-700 mb-2">City of Talisay Business Affairs Office</p>
						<p class="text-xs text-gray-500 mb-1">This report was generated automatically on <?php echo $current_date; ?> at <?php echo $current_time; ?></p>
						<p class="text-xs text-gray-500">For inquiries, please contact the Business Affairs Office</p>
					</div>
				</div>
			</div>
		</main>
	</div>
</div>

<script>
	// Mobile menu toggle
	document.getElementById('menu-button').addEventListener('click', function() {
		document.getElementById('sidebar').classList.toggle('-translate-x-full');
	});
</script>

    <script src="<?php echo $base_url ?? ''; ?>/assets/js/main.js"></script>
</body>
</html>


















